import { Metadata } from "next";
import { FC } from "react";

interface SignInProps {}

export const metadata: Metadata = {
  title: "Sign In",
  description: "Generated by create next app",
};

const SignIn: FC<SignInProps> = ({}) => {
  return <div>SignIn</div>;
};

export default SignIn;
