import { Metadata } from "next";
import { FC } from "react";

interface SignUpProps {}

export const metadata: Metadata = {
  title: "Sign Up",
  description: "Generated by create next app",
};

const SignUp: FC<SignUpProps> = ({}) => {
  return <div>SignUp</div>;
};

export default SignUp;
